language: go

go:
  - 1.x

before_script:

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
#before_deploy:
  - go get -u github.com/mattn/go-isatty
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/tcnksm/ghr

  - gox -output "binary/tokenticker_{{.OS}}_{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose
  - cp token_ticker.example.yaml binary
  - mkdir -p dist
  - for f in binary/*; do
      if [[ -f "$f" && -x "$f" ]]; then
        base=$(basename "$f");
        tar zcvf "dist/$base.tar.gz" -C binary "$base" token_ticker.example.yaml;
      fi
    done
  - ghr --username polyrabbit --token $GITHUB_TOKEN --replace -delete --prerelease --debug pre-release dist/

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

branches:
  except:
  - pre-release

notifications:
  email: false