language: go

go:
  - stable

env:
  - GO111MODULE=on

#os:
#  - osx
#  - linux
#  - windows

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go run *.go -d -c token_ticker.example.yaml

after_success:
  # Ensure download script works
  - curl -sfL https://raw.githubusercontent.com/polyrabbit/token-ticker/master/install.sh | bash -s -- -d
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go get -u github.com/mattn/go-isatty
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/tcnksm/ghr

  - gox -output "binary/tt_{{.OS}}_{{.Arch}}/tt" -ldflags "-X github.com/polyrabbit/token-ticker/config.Rev=`git rev-parse --short HEAD` -X github.com/polyrabbit/token-ticker/config.Version=`git describe --tags | cut -dv -f 2`" -verbose
  - cp token_ticker.example.yaml binary
  - mkdir -p dist
  - for f in binary/*; do
      if [[ -d "$f" ]]; then
        cp token_ticker.example.yaml "$f";
        base=$(basename "$f");
        tar zcvf "dist/$base.tar.gz" -C "$f" .;
      fi
    done
#  - ghr --username polyrabbit --token $GITHUB_TOKEN --replace -delete --prerelease --debug pre-release dist/

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

branches:
  except:
  - pre-release

notifications:
  email: false
